server:
  port: 8083

spring:
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
  data:
    mongodb:
      host: ${DATABASE_HOSTNAME}
      port: ${DATABASE_PORT}
      database: ${DATABASE_NAME}
      auto-index-creation: true