server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: intent-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/rea-keycloak
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak
            client-id: rea-app
            client-secret:
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'