FROM openjdk:17
COPY target/*.jar /offer-service-appliation.jar
VOLUME /tmp
CMD ["java", "-Dspring.profiles.active=local", "-Xdebug", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5083", "-jar", "/offer-service-appliation.jar"]
EXPOSE 8086