FROM node:20-alpine as angular
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
WORKDIR /app
COPY --from=angular /app/dist/rea-front /usr/share/nginx/html
EXPOSE 80
